eurekaIp : 10.136.238.28
#eurekaIp : localhost
spring:
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      discovery:
        locator:
          #是否与服务发现组件进行结合，通过serviceId转发到具体实例
          #是否开启基于服务发现的路由规则
          enabled: true
          ##表示将请求路径的服务名配置改成小写 ,因为服务注册的时候，向注册中心注册时将服务名转成大写的了
          lowerCaseServiceId: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOrigins: '*'
      httpclient: #http连接设置
#        全局超时
        connect-timeout: 1000
        response-timeout: 5s
        pool:
          max-connections: 5000 #最大连接数
          #       max-life-time: 45000 #最大连接时间
          acquire-timeout: 15000 #返回时间
          max-idle-time: 10000 #最大空闲时间


      routes:
        - id: eureka-client
          uri: lb://eureka-client
          predicates:
            - Path=/client/**
          filters:
        - id: contract-charge
          uri: lb://contract-charge
          predicates:
            - Path=/contract/**
        - id: audit-service
          uri: lb://audit-service
          predicates:
            - Path=/audit/**
#        单个超时
#          metadata:
#            response-timeout: 7000
#            connect-timeout: 2000
      default-filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: default
                fallbackUri: forward:/defaultfallback
                timeout:
                  # 这里暂时用-分隔URL，因为/不支持
                  demo-control-down_control: 11000
                  demo-control-down_up: 11000


hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 8000


server:
  port: 9999

debug: true

logging:
  level: #修改日志级别
    com.jourwon.springcloud.service: debug

eureka:
  instance:
    hostname: gateway
  client:
    # 注册到Eureka的注册中心
    register-with-eureka: true
    # 获取注册实例列表
    fetch-registry: true
    service-url:
      # 配置注册中心地址
      defaultZone: http://${eurekaIp}:9000/eureka/

