spring:
  application:
    name: eureka-client
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      enabled : true
      max-file-size: 20MB
      max-request-size: 20MB

    static-path-pattern: /excel/**

#  security:
#    user:
#      name: 7499
#      password: 7499
#  main:
#    allow-bean-definition-overriding: true

  resources:
    static-locations: file:D://excel/
#  datasource:
#    tomcat:
#      max-idle: 20
#      max-wait: 10000
#      min-idle: 5
#      initial-size: 5
##      filter: stat,wall
#  aop:
#    auto: true
#    proxy-target-class: true

#security:
#  oauth2:
#    client:
#      client-id: eureka-client
#      client-secret: zpepdi7499
#      user-authorization-uri: http://localhost:9100/oauth/authorize
#      access-token-uri: http://localhost:9100/token/login
#    resource:
#      id: eureka-client
#      user-info-uri: http://localhost:9100/oauth/check_token
#      jwt:
#        key-uri: http://localhost:9100/oauth/token_key
#        key-value: dev
#    authorization:
#      check-token-access: http://localhost:9100/oauth/check_token

server:
  port: 9009
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
    session:
      timeout: 3000m

  tomcat:
    uri-encoding: UTF-8
    max-http-form-post-size: -1

debug: true

#mybatis:
#  config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.zpepdi.eureka_client.entity


#eureka:
#  instance:
#    hostname: localhost
#  client:
#    # 注册到Eureka的注册中心
#    register-with-eureka: true
#    # 获取注册实例列表
#    fetch-registry: true
#    service-url:
#      # 配置注册中心地址
#      defaultZone: http://localhost:9000/eureka/